railsfriends/config/routes.rb
Rails.application.routes.draw do
  # devise_for :models
  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      devise_for :models, controllers: { sessions: 'api/v1/sessions', registrations: 'api/v1/registrations' }
      resources :friends do
        member do
          post 'upload_photo'
        end
        collection do
          get 'export_excel'
          get 'export_pdf'
        end
      end
      post 'forgot-password', to: 'passwords#forgot_password'
      post 'friends/upload_photo_test', to: 'friends#upload_photo_test'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      resources :registrations, only: [:create]
    end
  end

  # Define your other routes as needed
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  #root "friends#index"
end

railsfriends/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

railsfriends/app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :model, optional: true
	has_one_attached :photo
end

railsfriends/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :friends
end

railsfriends/app/controllers/api/v1/friends_controller.rb
class Api::V1::FriendsController < ApplicationController
  # before_action :authenticate_user! # Ensure user is authenticated
  before_action :set_friend, only: [:show, :update, :destroy, :upload_photo]
  # before_action :set_friend, only: [:show, :update, :destroy]


  def upload_photo
    if params[:photo].present?
      @friend.photo.attach(params[:photo])

      if @friend.save
        render json: { message: 'Photo uploaded successfully' }, status: :ok
      else
        render json: { error: 'Failed to upload photo' }, status: :unprocessable_entity
      end
    else
      render json: { error: 'No photo provided' }, status: :bad_request
    end
  rescue => e
    Rails.logger.error("Failed to upload photo: #{e.message}")
    render json: { error: 'Internal Server Error' }, status: :internal_server_error
  end

  # GET /api/v1/friends
  def index
    puts "Session user_id at friend controller: #{session.inspect}"
    
    @friends = Friend.where(user_id: params[:user_id]).paginate(page: params[:page], per_page: 5) 
    puts @friends.inspect
    render json: {
      friends: @friends.map { |friend| friend_response(friend) },
      current_page: @friends.current_page,
      total_pages: @friends.total_pages,
      total_entries: @friends.total_entries
    }
  end

  

  # GET /api/v1/friends/:id
  def show
    render json: friend_response(@friend)
  end

  # POST /api/v1/friends
  # POST /api/v1/friends
def create
  @friend = Friend.new(friend_params) # Use `new` instead of `build`

  if @friend.save
    render json: { success: true, friend: @friend }, status: :created
  else
    render json: { success: false, errors: @friend.errors.full_messages }, status: :unprocessable_entity
  end
end


  # PATCH/PUT /api/v1/friends/:id
  def update
    if @friend.update(friend_params)
      render json: @friend
    else
      render json: @friend.errors, status: :unprocessable_entity
    end
  end

  # DELETE /api/v1/friends/:id
  def destroy
    @friend.destroy
    head :no_content
  end

  private

  def set_friend
    @friend = Friend.find(params[:id])
  end

  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id, :model_id,:photo_url)
  end

  def friend_response(friend)
    # Create a hash and conditionally add the photo URL if the photo is attached
    response = friend.as_json
    response[:photo_url] = url_for(friend.photo) if friend.photo.attached?
    response
  end
end

railsfriends/app/controllers/api/v1/passwords_controller.rb
class Api::V1::PasswordsController < ApplicationController
  # POST /api/v1/forgot-password
  def forgot_password
    @model = Model.find_by(email: params[:email])
    if @model
      # Assuming you have a method to send the reset password email
      @model.send_reset_password_instructions
      render json: { message: 'Password reset link has been sent to your email.' }, status: :ok
    else
      render json: { error: 'Email not found.' }, status: :not_found
    end
  end
end

railsfriends/app/controllers/api/v1/registrations_controller.rb
class Api::V1::RegistrationsController < ApplicationController
  def create
    registration_params = params.require(:user).permit(:email, :password, :password_confirmation)
    
    @model = Model.new(registration_params) # Use the correct model name

    if @model.save
      render json: { message: "User registered successfully", success: true }, status: :created
    else
      render json: { error: @model.errors.full_messages.join(", "), success: false }, status: :unprocessable_entity
    end
  end
end

railsfriends/app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < ApplicationController
  def create
    @model = Model.find_by(email: session_params[:email])
    
    if @model
      puts "User found: #{@model.email}"
      if @model.valid_password?(session_params[:password])
        puts "Password valid"
        session[:user_id] = @model.id
        puts "Session after setting user_id: #{session.inspect}"
        render json: { message: "User logged in successfully", success: true, user_id: @model.id }
      else
        puts "Invalid password"
        render json: { error: "Login is invalid", success: false }
      end
    else
      puts "User not found"
      render json: { error: "Login is invalid", success: false }
    end
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

railsfriends/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  # protect_from_forgery with: :exception

  def current_user
    @current_user ||= Model.find_by(id: session[:user_id])
  end

  def authenticate_user!
    if current_user.nil?
      render json: { error: 'Unauthorized' }, status: :unauthorized
    end
  end
end

railsfriends/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

railsfriends/app/helpers/application_helper.rb
module ApplicationHelper
end

railsfriends/app/helpers/friends_helper.rb
module FriendsHelper
end

railsfriends/app/helpers/home_helper.rb
module HomeHelper
end

railsfriends/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :last_name , class:"form-control",placeholder: "Last Name"%>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :email , class:"form-control",placeholder: "Email"%>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder: "Phone" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder: "Twitter" %>
  </div>
  <br />
  <div class="field form-group">
    
  <%= form.number_field :model_id, id: :friend_model_id, class: "form-control", value: current_model.id, type: :hidden %>


  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

railsfriends/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">

  <div class="jumbotron">
  <h1 class="display-4"><%= friend.first_name %> <%= friend.last_name %></h1>
  <p class="lead"><%= friend.email %> | <%= friend.phone %> | <%= friend.twitter %></p>
  
</div>


  

</div>

railsfriends/app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

railsfriends/app/views/friends/export_pdf.html.erb
<!-- app/views/friends/export_pdf.html.erb -->
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
      </tr>
    <% end %>
  </tbody>
</table>

railsfriends/app/views/friends/index.html.erb
<%# <h1>Friends</h1> %>
<% if model_signed_in? %>
<div class="row justify-content-end">
  <div class="col-auto">
  <%= link_to "Download Excel", export_excel_friends_path(format: 'xlsx'), class: "btn btn-primary" %>
</div>
<div class="col-auto">
  <%= link_to "Download PDF", export_pdf_friends_path(format: 'pdf'), class: "btn btn-primary" %>
</div>
  </div>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>First name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
      <% if friend.model == current_model %>
        <tr>
          <td><%= link_to friend.first_name + '' + friend.last_name , friend %></td>
          <td><%= link_to friend.email, "mailto:#{friend.email}" %></td>
          <td><%= link_to friend.phone, "https://wa.me/#{friend.phone}", target: "_blank"  %></td>
          <td><%= link_to friend.twitter, "https://twitter.com/#{friend.twitter}", target: "_blank" %></td> 
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>
<% else %>
  <h1>Hello World! </h1>
  this is my first rails webpage
<% end %>

<div class="pagination">
  <%= will_paginate @friends, :class => 'text-right' %>
</div>

railsfriends/app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

railsfriends/app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-secondary" %> |
  <%= link_to "Back to friends", friends_path, class: "btn btn-dark" %>
  <br></br>

  <%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-outline-danger" %>
</div>

railsfriends/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to 'About us', home_about_path, class:"nav-link" %>
        </li>
        
        <% if model_signed_in? %>
          
          <li class="nav-item">
          <%= link_to 'Sign Out', destroy_model_session_path, method: :delete, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_model_registration_path, class:"nav-link" %>
        </li>

        <% else %>

          <li class="nav-item">
          	<%= link_to 'Sign Up', new_model_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
          	<%= link_to 'Sign In', new_model_session_path, class:"nav-link" %>
          </li>
        <% end %>

        
        
        
      </ul>
      
    </div>
  </div>
</nav>

railsfriends/app/views/home/about.html.erb
<h1>about here </h1>

railsfriends/app/views/home/index.html.erb
<h1>Hello World!</h1>

railsfriends/app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= flash[:notice] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

railsfriends/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    
      <%= render 'home/header'%>
      <div style = 'bottom:50px'></div>
      
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <% if model_signed_in? %>
      
        <span style="margin-left: 1200px !important;">
          Welcome, <%= current_model.email.sub(/@gmail\.com\z/, '') %>
        </span>
     
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

railsfriends/app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs - Ruby on Rails</title>
</head>
<body>
    <%= yield %>
</body>
</html>